# Generated by Django 4.2.5 on 2024-04-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='principal',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
